"""add dismissed reminder

Revision ID: 40c5c4327c2c
Revises: ef9f99a0f7ae
Create Date: 2025-07-06 21:06:46.344612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40c5c4327c2c'
down_revision = 'ef9f99a0f7ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dismissed_reminder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reminder_id', sa.String(length=128), nullable=False),
    sa.Column('dismissed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reminder_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dismissed_reminder')
    # ### end Alembic commands ###
