"""initial migration

Revision ID: 545cfa681a2f
Revises: 
Create Date: 2025-07-08 15:29:35.935182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '545cfa681a2f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dismissed_reminder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reminder_id', sa.String(length=128), nullable=False),
    sa.Column('dismissed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reminder_id')
    )
    op.create_table('member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('gender', sa.String(length=16), nullable=True),
    sa.Column('id_card_number', sa.String(length=18), nullable=True),
    sa.Column('member_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('mentors', sa.String(length=128), nullable=True),
    sa.Column('application_date', sa.Date(), nullable=True),
    sa.Column('activist_date', sa.Date(), nullable=True),
    sa.Column('development_object_date', sa.Date(), nullable=True),
    sa.Column('pre_member_date', sa.Date(), nullable=True),
    sa.Column('full_member_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_card_number')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('submission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('submission_date', sa.Date(), nullable=False),
    sa.Column('submission_type', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('submission')
    op.drop_table('user')
    op.drop_table('member')
    op.drop_table('dismissed_reminder')
    # ### end Alembic commands ###
